name: 'dhis2-docker image ci'

on: [push]

env:
    IMAGE_NAME: 'postgres-contrib'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
